### ISSUE TITLE
uart例程有bug

### ISSUE THREAD

**Issue by Ailikez** [eboxmaker/eBox_STM32F1#6]
ebox_init();

    PD2.mode(OUTPUT_PP);

    PA8.mode(OUTPUT_PP);

    PD2.set();

    PA8.set();

    uart3.begin(9600);

    uart3.attach(test,RxIrq);

> 要使能中断才可以使用attach吧？

> 实际测试，改成下面的代码才能用

    uart3.attach(pc_rcv_func,RxIrq);

    **uart3.interrupt(RxIrq, ENABLE, 5, 1);**

> 还有如果使用freertos串口中断优先级会和rtos冲突,影响实时性，我试着修改了一下

       void Uart::interrupt(IrqType type, FunctionalState enable,uint8_t preemption_priority, uint8_t sub_priority)

      {

      // ailike modified  under freertos

      //    if(preemption_priority > 4)preemption_priority = 4;

      //    if(sub_priority > 4)sub_priority = 4;

      **if(preemption_priority < 5)preemption_priority = 5;

      if(sub_priority > 4)sub_priority = 4;**

      NVIC_InitTypeDef NVIC_InitStructure;

**Comment by eboxmaker** [comment]
#define NVIC_PriorityGroup_2         ((uint32_t)0x500) /*!< 2 bits for pre-emption priority
ebox_init()中使用了中断分组。
取值范围是0-3.最大值应该是3.所以不知道你这个5是怎么设置过去的。
代码原来的是4也是不对的。
做如下修改
    if(preemption_priority > 3)preemption_priority = 3;
    if(sub_priority > 3)sub_priority = 3;

系统默认优先级0,0
    void interrupt(IrqType type, FunctionalState enable, uint8_t preemption_priority = 0, uint8_t sub_priority = 0);

如果你想修改默认的优先级设置
uart3.interrupt(RxIrq, ENABLE, 0-3,0-3);
